### ISSUE TITLE
attribution links

### ISSUE THREAD

**Issue by dethtron5000** [asamiller/marvelousdb#1]
Hi - this looks really awesome.
Can you add the links to Marvel as described here: http://developer.marvel.com/documentation/attribution?  

Thanks (it will help me show it off internally).

**Comment by asamiller** [comment]
Thanks @dethtron5000! I didn't read that page close enough. I added in more attribution on the character and comic view pages.

**Comment by dethtron5000** [comment]
Thanks for the quick response.  Do you mind putting it a bit higher on the
page (like on this one http://marvelousdb.com/character/1009223 maybe a
"read more on marvel.com" link under the character name or something).  I
want to make sure that it's clear when I show it internally.

The site looks great!

**Comment by asamiller** [comment]
@dethtron5000 Sure no problem. I moved the link up under the character/comic name and changed it to say: "View comic on Marvel.com". Let me know if this works for you.
